name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run prettier
        run: yarn format

  lint:
    name: Lint packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run ESLint
        run: yarn lint

  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run packemon
        run: yarn build

  typecheck:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - name: Setup node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run packemon
        run: yarn type
